# Database connection
db_uri = postgresql://postgres:mleko1235@localhost:5432/auth_service

# Server settings
port = 6767
ssl = true
key_path = /home/missqu/projects/sql_learning/key.pem
cert_path = /home/missqu/projects/sql_learning/cert.pem
